version: "2"
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  post_install:
    - pip install torch==2.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - pip install torch-sparse -f https://data.pyg.org/whl/torch-2.2.0+cpu.html

sphinx:
  configuration: docs/source/conf.py

bibtex_bibfiles:
    - references.bib
