# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install torch==2.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - pip install torch-sparse -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
sphinx:
  configuration: docs/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: false
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
